# meta
name: seq2seq/fine_tune

# model
ckpt: ckpt/seq2seq/fine_tune/10.pth

# data
data_dir: data/crohme
vocab: data/crohme/annotations/vocab.csv
base_size: [300, 300]
mean: [0.5]

# eval
device: cuda
styles: ["printed", "written", "fake_printed"]
parts: ["dev"]
batch_size: 20
max_output_len: 100
