# meta
name: seq2seq/im2latex_crohme

# model
ckpt: ckpt/seq2seq/im2latex/50.pth

# data
data_dir: data/crohme
vocab: data/im2latex/annotations/vocab.csv
base_size: [300, 300]
mean: [0.5]

# eval
device: cuda
styles: ["printed", "written", "fake_printed"]
parts: ["dev"]
batch_size: 20
max_output_len: 100
