# meta
name: Seq2Seq/crohme
model: Seq2Seq

# data
data_dir: "data/crohme"
base_size: [300, 300]

# train
device: cuda
epochs: 5
lr: 0.001
beta1: 0.5
beta2: 0.999
batch_size: 16
mean: [0.5]
continued: true

# log
sample_every: 20
display_size: 6

# model
decoder:
  heads: 8
  input_dim: 256
  hidden_dim: 256