# meta
name: Seq2Seq/local
model: Seq2Seq

# data
data_dir: "data-local/crohme"
base_size: [300, 300]

# train
device: cpu
epochs: 20
lr: 0.001
beta1: 0.5
beta2: 0.999
batch_size: 64
mean: [0.5]
continued: true

# log
sample_every: 20
display_size: 6

# model
encoder:
  output_dim: 64 # encoder output_dim should be the same as decoder input_dim
decoder:
  heads: 8
  input_dim: 64
  hidden_dim: 256
