# meta
name: cyclegan/crohme
model: ckpt/cyclegan/mnist/5.pth # set to cyclegan to train from scratch 
base_size: [300, 300]
crop_size: [224, 224]

# data
data_dir: data/crohme
paired: false

# train
device: cuda
epochs: 80
lr: 0.001
beta1: 0.5
beta2: 0.999
batch_size: 8
mean: [0.5]
lambd_x: 5
lambd_y: 5
continued: true

# log
sample_every: 20
display_size: 6

# model (determined by mnist.yml, should be the same with it), uncomment to train from scratch
# g_conv_dim: 32
# d_conv_dim: 32
